{
 "title": "Energy Monitor",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Voltage (V)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energymonitor",
     "select": [
      [
       { "params": [ "V" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phase", "operator": "=", "value": "L1" }
     ]
    },
    {
     "alias": "L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energymonitor",
     "select": [
      [
       { "params": [ "V" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phase", "operator": "=", "value": "L2" }
     ]
    },
    {
     "alias": "L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energymonitor",
     "select": [
      [
       { "params": [ "V" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phase", "operator": "=", "value": "L3" }
     ]
    }
   ]
  },
  {
   "title": "Amper L1",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energymonitor",
     "select": [
      [
       { "params": [ "I" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phase", "operator": "=", "value": "L1" }
     ]
    }
   ]
  },
  {
   "title": "Amper L2",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energymonitor",
     "select": [
      [
       { "params": [ "I" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phase", "operator": "=", "value": "L2" }
     ]
    }
   ]
  },
  {
   "title": "Amper L1",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energymonitor",
     "select": [
      [
       { "params": [ "I" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phase", "operator": "=", "value": "L3" }
     ]
    }
   ]
  },
  {
   "title": "Voltage L1",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energymonitor",
     "select": [
      [
       { "params": [ "V" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phase", "operator": "=", "value": "L1" }
     ]
    }
   ]
  },
  {
   "title": "Voltage L2",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energymonitor",
     "select": [
      [
       { "params": [ "V" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phase", "operator": "=", "value": "L2" }
     ]
    }
   ]
  },
  {
   "title": "Voltage L3",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energymonitor",
     "select": [
      [
       { "params": [ "V" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phase", "operator": "=", "value": "L1" }
     ]
    }
   ]
  },
  {
   "title": "Current (I)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "alias": "L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energymonitor",
     "select": [
      [
       { "params": [ "I" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phase", "operator": "=", "value": "L1" }
     ]
    },
    {
     "alias": "L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energymonitor",
     "select": [
      [
       { "params": [ "I" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phase", "operator": "=", "value": "L2" }
     ]
    },
    {
     "alias": "L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energymonitor",
     "select": [
      [
       { "params": [ "I" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phase", "operator": "=", "value": "L3" }
     ]
    }
   ]
  },
  {
   "title": "Power L1",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energymonitor",
     "query": "SELECT mean(\"I\") * mean(\"V\") FROM \"energymonitor\" WHERE (\"phase\" = 'L1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "V" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phase", "operator": "=", "value": "L1" }
     ]
    }
   ]
  },
  {
   "title": "Power L2",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energymonitor",
     "query": "SELECT mean(\"I\") * mean(\"V\") FROM \"energymonitor\" WHERE (\"phase\" = 'L2') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "V" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phase", "operator": "=", "value": "L1" }
     ]
    }
   ]
  },
  {
   "title": "Power L3",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energymonitor",
     "query": "SELECT mean(\"I\") * mean(\"V\") FROM \"energymonitor\" WHERE (\"phase\" = 'L3') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "V" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phase", "operator": "=", "value": "L1" }
     ]
    }
   ]
  },
  {
   "title": "Power (W)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "alias": "L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energymonitor",
     "query": "SELECT mean(\"I\") * mean(\"V\") FROM \"energymonitor\" WHERE (\"phase\" = 'L1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "I" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "phase", "operator": "=", "value": "L1" }
     ]
    },
    {
     "alias": "L2",
     "query": "SELECT mean(\"I\") * mean(\"V\") FROM \"energymonitor\" WHERE (\"phase\" = 'L2') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "L3",
     "query": "SELECT mean(\"I\") * mean(\"V\") FROM \"energymonitor\" WHERE (\"phase\" = 'L3') AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Power (L1 + L2 + L3)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "alias": "Power (3P)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energy3pmonitor",
     "select": [
      [
       { "params": [ "watt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}